/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "main.h"

void task1_handler(void);//this is task1
void task2_handler(void);//this is task2
void task3_handler(void);//this is task3
void task4_handler(void);//this is task4

void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t schd_top_of_stack);


uint32_t psp_of_tasks[MAX_TASKS]= {T1_STACK_START,T2_STACK_START,T3_STACK_START,T4_STACK_START);


int main(void)
{

	init_tasks_stack();
	init_systick_timer(TICK_HZ);

	for(;;);

}

void task1_handler(void){
	while(1){
		printf("this is task1\n");
	}
}

void task2_handler(void){
	while(1){
		printf("this is task2\n");
	}
}

void task3_handler(void){
	while(1){
		printf("this is task3\n");
	}
}

void task4_handler(void){
	while(1){
		printf("this is task4\n");
	}
}

void init_systick_timer(uint32_t tick_hz){
	uint32_t *pSRVR =(uint32_t*)0xE000E014 ;
	uint32_t *pSCSR =(uint32_t*)0xE000E010 ;

	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz ) - 1 ;

	//clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//load the value in to SVR
	*pSRVR |= count_value ;

	//do some settings
	*pSCSR |= (1<<1);//enable systick exception request
	*pSCSR |= (1<<2);//indicates the clock source , processor clock source

	//enable the systick
	*pSCSR |= (1<<1);//enables the counter

}

__attribute__((naked)) void init_scheduler_stack(uint32_t schd_top_of_stack){

	__asm volatile("MSR MSP ,%0": :"r"(sched_top_of_stack): );
	__asm volatile("BX LR");
}


void init_tasks_stack(void)
{


	uint32_t *pPSP;

	for(int i=0;i<MAX_TASKS;i++){
		pPSP = (uint32_t*) psp_of_tasks[i];
	}
}

void SysTick_Handler(void){


}
